# Site settings
title: Brandon Tate
email: blt900@gmail.com
# this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: Muddling through this programming thing. 
   Watch me as I fail over and over again trying to get it right.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brandontate.github.io/" # the base hostname & protocol for your site
twitter_username: Tate900
github_username:  brandontate

# Build settings
markdown: kramdown
